default: &default
  adapter: postgresql
  encoding: unicode
  username: bookworm
  # password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  host: localhost
  password: password
  database: bookworm_development

test:
  <<: *default
  host: localhost
  database: bookworm_test
  password: password

production:
  <<: *default
  host: db
  database: bookworm_production
