default: &default
  adapter: postgresql
  encoding: unicode
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5

development:
  host: localhost
  <<: *default
  database: bookworm_development


test:
  host: localhost
  <<: *default
  database: bookworm_test

production:
  <<: *default
  host: db
  username: postgres
  database: bookworm_production
