name: "RSpec/Rails CI"
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: bookworm_test
          POSTGRES_USER: bookworm
          POSTGRES_PASSWORD: password
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://bookworm:password@localhost:5432/bookworm_test"
    steps:
      - name: Create folder
        run: |
          mkdir -p /opt/bookworm
          cd /opt/bookworm
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Bundle
        run: |
          cd rails
          bundle install
      - name: set up database
        run: |
          cd rails
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run rspec
        run: |
          cd rails
          bundle exec rspec
